/*
 * RIC subscription
 *
 * This is the initial REST API for RIC subscription
 *
 * The version of the OpenAPI document: 0.0.4
 *
 * Generated by: https://openapi-generator.tech
 */

use serde_derive::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscriptionResponse {
    #[serde(rename = "SubscriptionId")]
    pub subscription_id: String,
    #[serde(rename = "SubscriptionInstances")]
    pub subscription_instances: Vec<crate::models::SubscriptionInstance>,
}

impl SubscriptionResponse {
    pub fn new(
        subscription_id: String,
        subscription_instances: Vec<crate::models::SubscriptionInstance>,
    ) -> SubscriptionResponse {
        SubscriptionResponse {
            subscription_id,
            subscription_instances,
        }
    }
}
