[package]
name = "sdl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.23" }
crc32fast = "1.3"
rnib = { path = "../rnib" }
prost = "*"
log = "0.4"
