/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigValidationError {
    /// Name of the parameter
    #[serde(rename = "field")]
    pub field: String,
    /// Description of validation error
    #[serde(rename = "error")]
    pub error: String,
}

impl ConfigValidationError {
    pub fn new(field: String, error: String) -> ConfigValidationError {
        ConfigValidationError {
            field,
            error,
        }
    }
}


