/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeregisterRequest {
    #[serde(rename = "appName")]
    pub app_name: String,
    #[serde(rename = "appInstanceName")]
    pub app_instance_name: String,
}

impl DeregisterRequest {
    pub fn new(app_name: String, app_instance_name: String) -> DeregisterRequest {
        DeregisterRequest {
            app_name,
            app_instance_name,
        }
    }
}


