/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterRequest {
    #[serde(rename = "appName")]
    pub app_name: String,
    #[serde(rename = "appVersion", skip_serializing_if = "Option::is_none")]
    pub app_version: Option<String>,
    #[serde(rename = "configPath", skip_serializing_if = "Option::is_none")]
    pub config_path: Option<String>,
    #[serde(rename = "appInstanceName")]
    pub app_instance_name: String,
    #[serde(rename = "httpEndpoint")]
    pub http_endpoint: String,
    #[serde(rename = "rmrEndpoint")]
    pub rmr_endpoint: String,
    /// Configuration in JSON string format
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
}

impl RegisterRequest {
    pub fn new(app_name: String, app_instance_name: String, http_endpoint: String, rmr_endpoint: String) -> RegisterRequest {
        RegisterRequest {
            app_name,
            app_version: None,
            config_path: None,
            app_instance_name,
            http_endpoint,
            rmr_endpoint,
            config: None,
        }
    }
}


