/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionData {
    #[serde(rename = "targetUrl")]
    pub target_url: String,
    #[serde(rename = "eventType")]
    pub event_type: crate::models::EventType,
    /// Maximum number of retries
    #[serde(rename = "maxRetries")]
    pub max_retries: i32,
    /// Time in seconds to wait before next retry
    #[serde(rename = "retryTimer")]
    pub retry_timer: i32,
}

impl SubscriptionData {
    pub fn new(target_url: String, event_type: crate::models::EventType, max_retries: i32, retry_timer: i32) -> SubscriptionData {
        SubscriptionData {
            target_url,
            event_type,
            max_retries,
            retry_timer,
        }
    }
}


