/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::SubscriptionData>,
}

impl SubscriptionRequest {
    pub fn new(data: crate::models::SubscriptionData) -> SubscriptionRequest {
        SubscriptionRequest {
            data: Box::new(data),
        }
    }
}


