/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionNotification {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    #[serde(rename = "eventType", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<crate::models::EventType>,
    #[serde(rename = "xApps", skip_serializing_if = "Option::is_none")]
    pub x_apps: Option<Vec<crate::models::Xapp>>,
}

impl SubscriptionNotification {
    pub fn new() -> SubscriptionNotification {
        SubscriptionNotification {
            id: None,
            version: None,
            event_type: None,
            x_apps: None,
        }
    }
}


