/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct XAppConfig {
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::ConfigMetadata>,
    /// Configuration in JSON format
    #[serde(rename = "config")]
    pub config: serde_json::Value,
}

impl XAppConfig {
    pub fn new(metadata: crate::models::ConfigMetadata, config: serde_json::Value) -> XAppConfig {
        XAppConfig {
            metadata: Box::new(metadata),
            config,
        }
    }
}


