/*
 * RIC appmgr
 *
 * This is a draft API for RIC appmgr
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct XappDescriptor {
    /// Name of the xApp in helm chart
    #[serde(rename = "xappName")]
    pub xapp_name: String,
    /// The exact xapp helm chart version to install
    #[serde(rename = "helmVersion", skip_serializing_if = "Option::is_none")]
    pub helm_version: Option<String>,
    /// Name of the xapp to be visible in Kubernetes
    #[serde(rename = "releaseName", skip_serializing_if = "Option::is_none")]
    pub release_name: Option<String>,
    /// Name of the namespace to which xApp is deployed. Overrides the value given in Helm chart value file.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// JSON string of override file for 'helm install' command
    #[serde(rename = "overrideFile", skip_serializing_if = "Option::is_none")]
    pub override_file: Option<serde_json::Value>,
}

impl XappDescriptor {
    pub fn new(xapp_name: String) -> XappDescriptor {
        XappDescriptor {
            xapp_name,
            helm_version: None,
            release_name: None,
            namespace: None,
            override_file: None,
        }
    }
}


