/*
 * RIC subscription
 *
 * This is the initial REST API for RIC subscription
 *
 * The version of the OpenAPI document: 0.0.4
 *
 * Generated by: https://openapi-generator.tech
 */

use serde_derive::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscriptionDetail {
    #[serde(rename = "XappEventInstanceId")]
    pub xapp_event_instance_id: u32,
    /// E2SM byte array
    #[serde(rename = "EventTriggers")]
    pub event_triggers: Vec<i32>,
    #[serde(rename = "ActionToBeSetupList")]
    pub action_to_be_setup_list: Vec<crate::models::ActionToBeSetup>,
}

impl SubscriptionDetail {
    pub fn new(
        xapp_event_instance_id: u32,
        event_triggers: Vec<i32>,
        action_to_be_setup_list: Vec<crate::models::ActionToBeSetup>,
    ) -> SubscriptionDetail {
        SubscriptionDetail {
            xapp_event_instance_id,
            event_triggers,
            action_to_be_setup_list,
        }
    }
}
