/*
 * RIC subscription
 *
 * This is the initial REST API for RIC subscription
 *
 * The version of the OpenAPI document: 0.0.4
 *
 * Generated by: https://openapi-generator.tech
 */

use serde_derive::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct XAppConfig {
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::ConfigMetadata>,
    /// Configuration in JSON format
    #[serde(rename = "config")]
    pub config: serde_json::Value,
}

impl XAppConfig {
    pub fn new(metadata: crate::models::ConfigMetadata, config: serde_json::Value) -> XAppConfig {
        XAppConfig {
            metadata: Box::new(metadata),
            config,
        }
    }
}
